var CONVERSION_CHANCE=20,OUTPUT_ITEM_IDS=["RSC_YUNQI_马字","RSC_YUNQI_年字","RSC_YUNQI_行字","RSC_YUNQI_大字","RSC_YUNQI_运字","RSC_YUNQI_岁字","RSC_YUNQI_有字","RSC_YUNQI_今字","RSC_YUNQI_朝字"],Material=Java.type("org.bukkit.Material"),ItemStack=Java.type("org.bukkit.inventory.ItemStack"),SlimefunItem=Java.type("io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem"),WORK_SLOT=40,OUTPUT_SLOTS=[],STONE_SLOTS=[],itemCache={},cooldowns={};
for(var i=46;i<=52;i++)OUTPUT_SLOTS.push(i);for(var i=0;i<=35;i++)STONE_SLOTS.push(i);
function onOpen(p){}function onClick(p,s,si,ca){if(s===WORK_SLOT&&ca.isShiftClicked()&&!ca.isRightClicked()){refillStoneSlots(p);return}if(STONE_SLOTS.includes(s))convertStone(p,s,si)}
function convertStone(p,s,si){var u=p.getUniqueId().toString(),n=Date.now();if(cooldowns[u]&&n-cooldowns[u]<3000){p.sendMessage("§c操作冷却中，请等待 3 秒");return}if(!si||si.getType()!==Material.STONE)return;var inv=p.getOpenInventory().getTopInventory();if(si.getAmount()>1)si.setAmount(si.getAmount()-1);else inv.setItem(s,createBlankGlassPane());if(Math.random()*100>CONVERSION_CHANCE){cooldowns[u]=n;return}var id=OUTPUT_ITEM_IDS[Math.floor(Math.random()*OUTPUT_ITEM_IDS.length)],rw=getSlimefunItem(id);if(!rw){cooldowns[u]=n;return}for(var i=0;i<OUTPUT_SLOTS.length;i++){var os=OUTPUT_SLOTS[i],oi=inv.getItem(os);if(!oi){inv.setItem(os,rw);p.sendMessage("§a采集成功 "+getItemName(rw));cooldowns[u]=n;return}else if(isSameItem(oi,rw)&&oi.getAmount()<64){oi.setAmount(oi.getAmount()+1);p.sendMessage("§a采集成功 "+getItemName(rw));cooldowns[u]=n;return}}p.sendMessage("§c输出槽位已满");cooldowns[u]=n}
function createBlankGlassPane(){var p=new ItemStack(Material.GRAY_STAINED_GLASS_PANE,1),m=p.getItemMeta();m.setDisplayName(" ");p.setItemMeta(m);return p}
function isBlankGlassPane(i){if(!i||i.getType()!==Material.GRAY_STAINED_GLASS_PANE)return false;var m=i.getItemMeta();return!!m&&m.hasDisplayName()&&m.getDisplayName().trim()===""}
function createBlankStone(){var s=new ItemStack(Material.STONE,1),m=s.getItemMeta();m.setDisplayName(" ");s.setItemMeta(m);return s}
function getItemName(i){var m=i.getItemMeta();if(m&&m.hasDisplayName())return m.getDisplayName();var sf=SlimefunItem.getByItem(i);return sf?sf.getItemName():i.getType().toString().toLowerCase().replace(/_/g,' ')}
function getSlimefunItem(id){if(itemCache[id])return itemCache[id].clone();var sf=SlimefunItem.getById(id);if(sf){itemCache[id]=sf.getItem();return itemCache[id].clone()}return null}
function isSameItem(a,b){if(!a||!b||a.getType()!==b.getType())return false;var sa=SlimefunItem.getByItem(a),sb=SlimefunItem.getByItem(b);return sa&&sb?sa.getId()===sb.getId():!(sa||sb)}
function refillStoneSlots(p){var inv=p.getOpenInventory().getTopInventory();STONE_SLOTS.forEach(function(s){var it=inv.getItem(s);if(!it)inv.setItem(s,createBlankStone());else if(isBlankGlassPane(it))inv.setItem(s,createBlankStone())})}
function onClose(p){}